# Conversion to & from Numpy and Pandas
By the end of this lecture you will be able to:
- convert between Polars and Numpy
- convert between Polars and Pandas

Key functionality in this notebook requires that your Pandas version is 2.0+ (automated testing is carried out with the latest version of Pandas on PyPi).

Use `pl.show_versions()` to check your installation

In [35]:
import polars as pl
import numpy as np
import pandas as pd


The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.


In [46]:
csv_file = "../Files/Sample_Superstore.csv"

In [47]:
df = pl.read_csv(csv_file)
df.head(3)

shape: (3, 21)
┌────────┬────────────────┬────────────┬────────────┬───┬────────┬──────────┬──────────┬─────────┐
│ Row_ID ┆ Order_ID       ┆ Order_Date ┆ Ship Date  ┆ … ┆ Sales  ┆ Quantity ┆ Discount ┆ Profit  │
│ ---    ┆ ---            ┆ ---        ┆ ---        ┆   ┆ ---    ┆ ---      ┆ ---      ┆ ---     │
│ i64    ┆ str            ┆ str        ┆ str        ┆   ┆ f64    ┆ i64      ┆ f64      ┆ f64     │
╞════════╪════════════════╪════════════╪════════════╪═══╪════════╪══════════╪══════════╪═════════╡
│ 1      ┆ CA-2016-152156 ┆ 11/8/2016  ┆ 11/11/2016 ┆ … ┆ 261.96 ┆ 2        ┆ 0.0      ┆ 41.9136 │
│ 2      ┆ CA-2016-152156 ┆ 11/8/2016  ┆ 11/11/2016 ┆ … ┆ 731.94 ┆ 3        ┆ 0.0      ┆ 219.582 │
│ 3      ┆ CA-2016-138688 ┆ 6/12/2016  ┆ 6/16/2016  ┆ … ┆ 14.62  ┆ 2        ┆ 0.0      ┆ 6.8714  │
└────────┴────────────────┴────────────┴────────────┴───┴────────┴──────────┴──────────┴─────────┘

## Convert a `DataFrame` to Numpy

To convert a `DataFrame` to Numpy use the `to_numpy` method. This clones (copies) the data.

In [38]:
arr = df.to_numpy()
arr

array([[1, 'CA-2016-152156', '11/8/2016', ..., 2, 0.0, 41.9136],
       [2, 'CA-2016-152156', '11/8/2016', ..., 3, 0.0, 219.582],
       [3, 'CA-2016-138688', '6/12/2016', ..., 2, 0.0, 6.8714],
       ...,
       [9992, 'CA-2017-121258', '2/26/2017', ..., 2, 0.2, 19.3932],
       [9993, 'CA-2017-121258', '2/26/2017', ..., 4, 0.0, 13.32],
       [9994, 'CA-2017-119914', '5/4/2017', ..., 2, 0.0, 72.948]],
      dtype=object)

This conversion turns each row into a Numpy `ndarray` and vertically stacks these row-arrays.

As the `DataFrame` has a mix of types the Numpy array has an `object` dtype.

If the columns have uniform numeric dtype then the Numpy array has the corresponding dtype.

In this example we use `select` to choose the 64-bit floating point columns only for conversion to Numpy...

> We cover `select` in more detail in the Section on Selecting columns and transforming dataframes.

In [39]:
floats_array = (
    df
    .select(
        pl.col(pl.Float64)
    )
    .to_numpy()
)
floats_array

array([[2.61960e+02, 0.00000e+00, 4.19136e+01],
       [7.31940e+02, 0.00000e+00, 2.19582e+02],
       [1.46200e+01, 0.00000e+00, 6.87140e+00],
       ...,
       [2.58576e+02, 2.00000e-01, 1.93932e+01],
       [2.96000e+01, 0.00000e+00, 1.33200e+01],
       [2.43160e+02, 0.00000e+00, 7.29480e+01]])

... and we get a float Numpy array

In [40]:
type(floats_array)

numpy.ndarray

In [20]:
floats_array.dtype

dtype('float64')

The Polars sequence dtypes `pl.List` and `pl.Array` are common ways to store sequences that might be passed to Numpy. We learn more about these in Section 4 of the course.

## Convert Numpy to a `DataFrame`

We can create a Polars `DataFrame` from a Numpy array

In [45]:

data_list = floats_array.tolist()

# Create a Polars DataFrame from the list of lists
convert_df = pl.DataFrame(data_list)

In [42]:
convert_df

shape: (3, 9_994)
┌──────────┬──────────┬──────────┬──────────┬───┬────────────┬────────────┬────────────┬───────────┐
│ column_0 ┆ column_1 ┆ column_2 ┆ column_3 ┆ … ┆ column_999 ┆ column_999 ┆ column_999 ┆ column_99 │
│ ---      ┆ ---      ┆ ---      ┆ ---      ┆   ┆ 0          ┆ 1          ┆ 2          ┆ 93        │
│ f64      ┆ f64      ┆ f64      ┆ f64      ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---       │
│          ┆          ┆          ┆          ┆   ┆ f64        ┆ f64        ┆ f64        ┆ f64       │
╞══════════╪══════════╪══════════╪══════════╪═══╪════════════╪════════════╪════════════╪═══════════╡
│ 261.96   ┆ 731.94   ┆ 14.62    ┆ 957.5775 ┆ … ┆ 91.96      ┆ 258.576    ┆ 29.6       ┆ 243.16    │
│ 0.0      ┆ 0.0      ┆ 0.0      ┆ 0.45     ┆ … ┆ 0.0        ┆ 0.2        ┆ 0.0        ┆ 0.0       │
│ 41.9136  ┆ 219.582  ┆ 6.8714   ┆ -383.031 ┆ … ┆ 15.6332    ┆ 19.3932    ┆ 13.32      ┆ 72.948    │
└──────────┴──────────┴──────────┴──────────┴───┴────────────┴────────────┴────────────┴───────────┘

In [48]:
type(convert_df)

polars.dataframe.frame.DataFrame

## Convert a `Series` to Numpy
Converting a `Series` to Numpy has more options than converting an entire `DataFrame`.

To do a simple conversion where the data is cloned use `to_numpy` on the `Series`

In [49]:
(
    df['Profit']
    .head()
    .to_numpy()
)

array([  41.9136,  219.582 ,    6.8714, -383.031 ,    2.5164,   14.1694,
          1.9656,   90.7152,    5.7825,   34.47  ])

And here we get the same output as above.

### Convert a `Series` to Numpy with zero-copy
In some cases we can convert a `Series` to Numpy without copying ("zero-copy"). 

Zero-copy is only possible if there are no `null` or `NaN` values such as in the `Survived` column. If we want to ensure that conversion to Numpy happens with zero-copy - and raise an `Exception` if a copy is needed - we use the `allow_copy` argument

In [50]:
arr = (
    df['Profit']
    .head()
    .to_numpy(allow_copy=False)
)
arr

array([  41.9136,  219.582 ,    6.8714, -383.031 ,    2.5164,   14.1694,
          1.9656,   90.7152,    5.7825,   34.47  ])